src/routes/web.php
<?php

use LaraWhale\App\Models\Route as LwRoute;


# Cms routes
# -------------------------------------------------- -->


Route::group([

	'namespace' => 'LaraWhale\App\Http\Controllers\Cms',
	'prefix' => 'cms',
	'middleware' => [
		'web'
	]

], function () {

	Route::get('login', [
		'as' => 'lw_get_login',
		'uses' => 'AuthController@get_login'
	]);

	Route::post('login', [
		'as' => 'lw_post_login',
		'uses' => 'AuthController@post_login'
	]);

	Route::get('logout', [
		'as' => 'lw_get_logout',
		'uses' => 'AuthController@get_logout'
	]);


	Route::group([

		'middleware' => [
			'LaraWhale\App\Http\Middleware\AuthMiddleware'
		]

	], function () {

		Route::get('/', [
			'as' => 'lw_get_index',
			'uses' => 'HomeController@index'
		]);


		Route::resource('pages', 'PageController');


		Route::resource('lists', 'ListController');


		Route::resource('list_items', 'ListItemController');

		Route::get('lists/{id}/list_items/create', [
			'as' => 'list_items.create',
			'uses' => 'ListItemController@create'
		]);

		Route::get('lists/{list_id}/list_items/{list_item_id}/edit', [
			'as' => 'list_items.edit',
			'uses' => 'ListItemController@edit'
		]);

		Route::put('lists/{list_id}/list_items/{list_item_id}/update', [
			'as' => 'list_items.update',
			'uses' => 'ListItemController@update'
		]);

		Route::delete('lists/{list_id}/list_items/{list_item_id}/delete', [
			'as' => 'list_items.delete',
			'uses' => 'ListItemController@destroy'
		]);

	});

});


# Frontend routes
# -------------------------------------------------- -->


Route::group([

	'namespace' => 'LaraWhale\App\Http\Controllers'

], function ()
{

	if(Schema::hasTable('lw_routes'))
	{
		
		$routes = LwRoute::all();

		foreach ($routes as $route)
		{

			Route::get($route->uri, [
				'as' => $route->name,
				'uses' => 'PageController@index'
			]);

		}

	}

});


# -------------------------------------------------- -->

src/resources/views/module/error_label.blade.php

@if (isset($key) && $errors->has($key))

	@foreach ($errors->get($key) as $error)

		<span class="label label-danger">
			
			{{ $error }}

		</span>

	@endforeach

@endif

src/resources/views/module/nav.blade.php
<nav class="navbar navbar-default">

	<div class="container-fluid">

		<div class="navbar-header">

			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>

			</button>

			<a class="navbar-brand" href="#">Brand</a>

		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

			<ul class="nav navbar-nav">

				<li>

					<a href="{{ route('pages.index') }}">

						Pages

					</a>

				</li>

				<li>

					<a href="{{ route('lists.index') }}">

						Lists

					</a>

				</li>

			</ul>

		</div>

	</div>

</nav>

src/resources/views/module/sections_form.blade.php
<div class="row">

    <?php $sections = ViewHelper::get_view_sections($view); ?>

    @foreach($sections as $section)

        <?php $owner_section = $owner->sections()->where('key', $section['key'])->first(); ?>

        <div class="col-xs-12">

            <h3>{{ ucfirst($section['key']) }}</h3>

            @foreach ($section['fields'] as $field)

                <div class="form-group">

                    <?php

                        $relation = $field['type'] . '_fields';

                        $section_field = $owner_section ? $owner_section->$relation()->where('key', $field['key'])->first() : NULL;

                        $input_name = 'sections['.$section['key'].']['.$field['key'].']';

                    ?>

                    {!! Form::label($field['key'], ucfirst($field['key'])) !!}

                    {!! Form::hidden($input_name.'[key]', $field['key']); !!}

                    {!! Form::hidden($input_name.'[type]', $field['type']); !!}

                    @if ($field['type'] == 'textarea')

                        {!! Form::textarea($input_name.'[value]', $section_field ? $section_field->value : NULL, [
                            'class' => 'form-control'
                        ]) !!}

                    @elseif ($field['type'] == 'file')

                        {!! Form::file($input_name.'[value]', [
                            'class' => 'form-control'
                        ]) !!}

                    @else

                        {!! Form::input($field['type'], $input_name.'[value]', $section_field ? $section_field->value : NULL, [
                            'class' => 'form-control'
                        ]) !!}

                    @endif

                </div>

            @endforeach

        </div>

    @endforeach

</div>

src/resources/views/module/table.blade.php

<table class="table">
    <thead>
        <tr>
            @foreach($columns as $column)

                <th>{{ $column }}</th>

            @endforeach
        </tr>
    </thead>

    <tbody>

        @foreach($items as $item)

            <tr>
                @foreach($columns as $column)
                    <td>{{ $item->$column }}</td>
                @endforeach

                <td>
                    <?php
                        $show_url = '';

                        if (isset($show_route))
                        {
                            $show_url = !is_callable($show_route) ?: $show_route($item);
                        }
                        else
                        {
                            $show_url = route($resource.'.show', $item);
                        }
                    ?>

                    <a href="{{ $show_url }}" class="btn btn-xs btn-success">
                        <span class="glyphicon glyphicon-eye-open"></span>
                    </a>

                    <?php
                        $edit_url = '';

                        if (isset($edit_route))
                        {
                            $edit_url = !is_callable($edit_route) ?: $edit_route($item);
                        }
                        else
                        {
                            $edit_url = route($resource.'.edit', $item);
                        }
                    ?>

                    <a href="{{ $edit_url }}" class="btn btn-xs btn-primary">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>

                    <?php
                        $delete_url = '';

                        if (isset($delete_route))
                        {
                            $delete_url = !is_callable($delete_route) ?: $delete_route($item);
                        }
                        else
                        {
                            $delete_url = route($resource.'.destroy', $item);
                        }
                    ?>

                    {!! Form::open([
                        'class' => 'action-confirm',
                        'method' => 'DELETE',
                        'url' => $delete_url,
                        'style' => 'display: inline-block;'
                    ]) !!}

                        <button class="btn btn-xs btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>

                    {!! Form::close() !!}
                </td>
            </tr>

        @endforeach

    </tbody>
</table>